# Generated by Django 3.2 on 2022-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profilebio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebio',
            name='email_adress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
