# Generated by Django 3.2 on 2022-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profilebio_email_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebio',
            name='email_adress',
        ),
        migrations.RemoveField(
            model_name='profilebio',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilebio',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profilebio',
            name='user',
        ),
        migrations.AddField(
            model_name='profilebio',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profilebio',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilebio',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilebio',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
