# Generated by Django 3.2 on 2022-10-15 16:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20221015_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebio',
            name='name',
        ),
        migrations.AlterField(
            model_name='profilebio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
