# Generated by Django 3.2 on 2022-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20221015_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilebio',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profilebio',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilebio',
            name='avatar',
            field=models.ImageField(default='profile.jpg', null=True, upload_to=''),
        ),
    ]
